/**
 * File storage on the local filesystem.
 *
 * Files live under `storage/` at the project root — deliberately *outside*
 * `public/`. Anything in `public/` is served directly by Next with no auth
 * check, which would make every uploaded file world-readable to anyone who
 * guessed a URL. Downloads instead go through an authenticated route that
 * checks permissions and then streams the bytes from here.
 *
 * The interface is intentionally small (`save`, `read`, `remove`, `exists`) so
 * it can be swapped for S3/R2 later without touching call sites.
 */

import { createReadStream, type ReadStream } from "fs";
import { mkdir, readFile, rm, stat, writeFile } from "fs/promises";
import { dirname, join, normalize, resolve, sep } from "path";

/**
 * Root of the storage tree. Override with STORAGE_DIR — required in production,
 * where the app directory is usually read-only or wiped between deploys and the
 * files must live on a mounted volume or object store instead.
 *
 * This line used to carry `turbopackIgnore: true` comments meant to silence the
 * build's "unexpected file in NFT list" warning. They did nothing: that comment
 * only applies to dynamic `import()`, `require()` and `new Worker()`, not to a
 * path built from `process.cwd()`. The warning is suppressed where it actually
 * can be — `turbopack.ignoreIssue` in next.config.ts, which explains why it is
 * a false positive here.
 */
const STORAGE_ROOT = resolve(process.env.STORAGE_DIR || join(process.cwd(), "storage"));

export class StorageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "StorageError";
  }
}

/**
 * Resolve a storage key to an absolute path, refusing anything that escapes the
 * storage root.
 *
 * Keys are generated by `createStorageKey` and should never be attacker-
 * controlled, but this is defence in depth: if a key ever does reach here from
 * a request parameter, `../../.env` must not resolve outside the root. The
 * check is on the *resolved* path, because that is what the filesystem will
 * actually use.
 */
function resolveKey(key: string) {
  if (!key || typeof key !== "string") {
    throw new StorageError("Missing storage key.");
  }

  // Reject NUL bytes outright — they can truncate paths in some syscalls.
  if (key.includes("\u0000")) {
    throw new StorageError("Invalid storage key.");
  }

  const absolute = resolve(STORAGE_ROOT, normalize(key));

  // Must be the root itself or strictly beneath it. The trailing separator
  // matters: without it, "/storage-evil" would pass a naive startsWith check
  // against "/storage".
  if (absolute !== STORAGE_ROOT && !absolute.startsWith(STORAGE_ROOT + sep)) {
    throw new StorageError("Storage key escapes the storage root.");
  }

  return absolute;
}

/** Write a buffer to `key`, creating parent directories as needed. */
export async function saveFile(key: string, contents: Buffer) {
  const absolute = resolveKey(key);

  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, contents);

  return { key, sizeBytes: contents.length };
}

/** Read a whole file into memory. Prefer `createFileStream` for large files. */
export async function readFileByKey(key: string) {
  return readFile(resolveKey(key));
}

/**
 * Open a read stream for a download response.
 *
 * Streaming rather than buffering: a 50 MB video read with `readFile` holds the
 * entire file in memory for the duration of the request, and a handful of
 * concurrent downloads would exhaust the heap.
 */
/**
 * Read a file, optionally only part of it.
 *
 * `start`/`end` are inclusive byte offsets, matching both `createReadStream`
 * and the HTTP `Range` header, so a range parsed off a request can be passed
 * straight through without an off-by-one conversion.
 */
export function createFileStream(
  key: string,
  range?: { start: number; end: number },
): ReadStream {
  return range
    ? createReadStream(resolveKey(key), { start: range.start, end: range.end })
    : createReadStream(resolveKey(key));
}

export async function fileExists(key: string) {
  try {
    await stat(resolveKey(key));
    return true;
  } catch {
    return false;
  }
}

export async function getFileSize(key: string) {
  const stats = await stat(resolveKey(key));
  return stats.size;
}

/**
 * Delete a file. Missing files are not an error — deleting an already-deleted
 * material should be idempotent rather than throwing.
 */
export async function removeFile(key: string) {
  await rm(resolveKey(key), { force: true });
}

/** Absolute path, for tooling that needs it. Not for building URLs. */
export function getAbsolutePath(key: string) {
  return resolveKey(key);
}

export { STORAGE_ROOT };
